# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e296508303c62df8c9f25ec1fa6121cc84080d24c697dec56bcb7f63e9274053c9c32e283efb9679c99fdf1ada1dcd47868be64f87cfe9f7bae2fc7f115b1aca

test:
  secret_key_base: 10204b36a42e701197a2db1b5a72ea4eba81b64a0ca417558e606608c4f97e8b4cdab16cb6ccd05b970a62101dcf08917d05d08789ce0e55bca1c934d18a5e47

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
